### ISSUE TITLE
seg_main_reproduce.py: not found in reproduce.sh

### ISSUE THREAD

**Issue by Wishmitha** [traptinblur/VCID_2023_3rd_place_code#1]
reproduce.sh contains the following command: 

CUDA_VISIBLE_DEVICES=0 python seg_main_reproduce.py --config r50_224_fold1 

But I realized there is no file called seg_main_reproduce.py in the repository.  Can you please resolve this by providing the file or any other way around this?

**Comment by traptinblur** [comment]
I have updated the reproduce.sh. It should work now.

**Comment by Wishmitha** [comment]
Thank you very much. That works!
